### ISSUE TITLE
[Bug] Export PDF don't works

### ISSUE THREAD

**Issue by mike37510** [lencx/ChatGPT#185] opened 2023-01-10 11:09 UTC
### Version

0.8.0

### Bug description

[Bug] Export PDF don't works on Windows 10 with 0.8.0.

### OS

Windows 10

**Comment by KutsuyaYuki** [comment] 2023-01-10 14:14
I have the same bug on MacOS 13.1 on a M1 processor,

**Comment by lencx** [comment] 2023-01-10 15:33
I reproduced the problem and if there is already a chat log it fails. If a new one is created everything is fine. This is because the scenario of opening an existing record was not considered before, this will be fixed in the next version.

**Comment by lencx** [comment] 2023-01-12 14:45
Please try v0.8.1

**Closed by lencx** 2023-01-12 14:45 UTC
Labels: bug
