### ISSUE TITLE
Had over 20 custom prompts, new update deleted them?

### ISSUE THREAD

**Issue by reconrad48** [lencx/ChatGPT#68] opened 2022-12-23 15:59 UTC
Please tell me this update didn't delete  my custom prompts? When the update installed, my custom prompts that I worked very hard on developing weren't there.. and I opened the config folder on windows and I don't see it there either. Man, please tell me that this update was not written in such a way to delete stuff like that.

**Comment by lencx** [comment] 2022-12-23 16:11
I'm very sorry, it was an oversight on my part, because of the data structure change, some of the configuration will be overwritten, otherwise the program will report an error. So I have released a minor version. Because the program is not yet in stable version, many configurations may change.

**Comment by reconrad48** [comment] 2022-12-23 16:16
I found them in a .json file, but I am having hard time importing them back in... seems when I go to Sync Custom and add the file path, it just shows the file path and file but doesn't import the individual prompts.

**Comment by lencx** [comment] 2022-12-23 16:23
You can store the files in json format in the `~/.chatgpt/myconf.json` directory
```json
[
  {
    "cmd": "a",
    "act": "aa",
    "prompt": "aaa aaa aaa"
  },
  {
    "cmd": "b",
    "act": "bb",
    "prompt": "bbb bbb bbb"
  }
]
```
<img width="912" alt="Screenshot 2022-12-24 at 00 19 51" src="https://user-images.githubusercontent.com/16164244/209366765-1d223bae-e606-428a-8e08-dd5d038f7203.png">

<img width="1158" alt="Screenshot 2022-12-24 at 00 20 38" src="https://user-images.githubusercontent.com/16164244/209367049-c0f33a3a-b869-419b-a92c-3e19058c6b29.png">

<img width="1154" alt="Screenshot 2022-12-24 at 00 23 16" src="https://user-images.githubusercontent.com/16164244/209367199-133db1af-8445-4f5c-b51e-f26a73aabe98.png">

**Comment by reconrad48** [comment] 2022-12-23 16:29
On my screen it doesn't show the "view"... 
![image](https://user-images.githubusercontent.com/71345926/209367952-81565e9a-06fa-4fe6-968d-42a766a25c63.png)

**Comment by lencx** [comment] 2022-12-23 16:30
Please click the sync button first.

**Comment by reconrad48** [comment] 2022-12-23 16:33
I tried the sync button first.. nothing happened.. 
The json file is in the following format
![image](https://user-images.githubusercontent.com/71345926/209368478-cc95fe5b-252f-4e63-8ae7-a7c27a20b297.png)

**Comment by reconrad48** [comment] 2022-12-23 16:34
My custom prompts were appended to this file, but they are at the end.

**Comment by reconrad48** [comment] 2022-12-23 16:37
Do I have to remove "tags", "enable" etc? Did you remove those parameters in parsing?

**Comment by lencx** [comment] 2022-12-23 16:37
It is a pure array, not an object:

```json
[
  {
    "cmd": "a",
    "act": "aa",
    "prompt": "aaa aaa aaa"
  },
  {
    "cmd": "b",
    "act": "bb",
    "prompt": "bbb bbb bbb"
  }
]
```

**Comment by reconrad48** [comment] 2022-12-23 16:54
Yeah I don't, it doesn't work. I have tried to set the path... sync, clean the json file, etc and it won't bring in the prompts.

**Comment by reconrad48** [comment] 2022-12-23 16:56
![image](https://user-images.githubusercontent.com/71345926/209372809-e51baf44-507c-4566-b1e7-1ed0ca44dcf6.png)

**Comment by reconrad48** [comment] 2022-12-23 16:56
![image](https://user-images.githubusercontent.com/71345926/209372913-96905c4c-e3f4-455c-9a54-2be3779e1dcc.png)

**Comment by reconrad48** [comment] 2022-12-23 16:57
it has the path right, but doesn't see the prompts 

![image](https://user-images.githubusercontent.com/71345926/209373014-bc2e38d6-fa47-4c15-9660-58a93f05bce8.png)

**Comment by lencx** [comment] 2022-12-23 16:59
Could you please check the console of devtools for errors?

`Menu -> Help`

<img width="379" alt="Screenshot 2022-12-24 at 00 56 33" src="https://user-images.githubusercontent.com/16164244/209372883-a5e6cf4d-a293-4944-a9d1-d6e67dcaa2be.png">

**Comment by lencx** [comment] 2022-12-23 17:00
> it has the path right, but doesn't see the prompts
> 
> ![image](https://user-images.githubusercontent.com/71345926/209373014-bc2e38d6-fa47-4c15-9660-58a93f05bce8.png)

This data structure has changed, so it will not be displayed.

**Comment by reconrad48** [comment] 2022-12-23 17:01
![image](https://user-images.githubusercontent.com/71345926/209373390-d358e888-b260-4f8d-8302-05d2680fcda6.png)

**Comment by reconrad48** [comment] 2022-12-23 17:02
> > it has the path right, but doesn't see the prompts
> > ![image](https://user-images.githubusercontent.com/71345926/209373014-bc2e38d6-fa47-4c15-9660-58a93f05bce8.png)
> 
> This data structure has changed, so it will not be displayed.

I don't know what that means... that is what I assigned in the sync custom tab...

**Comment by lencx** [comment] 2022-12-23 17:05
Does the sync button in `Sync Prompts` work?

<img width="600" alt="Screenshot 2022-12-24 at 01 03 35" src="https://user-images.githubusercontent.com/16164244/209373641-046d166e-5270-4578-b292-0f9743c4c99a.png">

**Comment by lencx** [comment] 2022-12-23 17:07
> ![image](https://user-images.githubusercontent.com/71345926/209373390-d358e888-b260-4f8d-8302-05d2680fcda6.png)

This problem is caused by the lack of file operation permission, and I am working on it.

**Comment by reconrad48** [comment] 2022-12-23 17:10
No, the "Sync Prompts" does not pull prompts from f/awesome-chatgpt... etc

**Comment by lencx** [comment] 2022-12-23 17:15
Is the version you have installed v0.6.4?

**Comment by reconrad48** [comment] 2022-12-23 17:24
I think so, got a dialog message saying new update is available would you like to install etc... happened an hour ago

**Comment by lencx** [comment] 2022-12-23 17:27
`Menu -> ChatGPT -> About`

<img width="586" alt="Screenshot 2022-12-24 at 01 26 24" src="https://user-images.githubusercontent.com/16164244/209376307-7b7071ae-ddc7-41d9-bc86-d0cd7ead34b8.png">

**Comment by reconrad48** [comment] 2022-12-23 17:32
I don't have it on my mac, this is windows 10... also, just a FYi, when i manually added a prompt, it did not save when I restarted ChatGPT

**Comment by lencx** [comment] 2022-12-23 17:39
The windows menu is similar, you should be able to see the menu about. I'd like to confirm your app version first, because just now I posted several versions to fix the path permissions issue. If it's already the latest version, I need to try other solutions.

**Comment by reconrad48** [comment] 2022-12-23 17:40
Unfortunately there isn't an "about" in windows

**Comment by reconrad48** [comment] 2022-12-23 17:46
I did just install the "lastest" windows version though... 3 seconds ago.

**Comment by lencx** [comment] 2022-12-23 17:52
Thanks, I'm looking for a solution, as a transitional solution you could try creating `~/.chatgpt/chat.model.cmd.json`:

```json
{
  "name": "ChatGPT CMD",
  "last_updated": 1671816282245,
  "data": [
    {
      "act": "aa",
      "cmd": "a",
      "enable": true,
      "prompt": "aaa aaa aaa"
    },
    {
      "act": "bb",
      "cmd": "b",
      "enable": true,
      "prompt": "bbb bbb bbb"
    }
  ]
}
```

**Comment by reconrad48** [comment] 2022-12-23 18:08
Unfortunately, that doesn't work either... Can I go back to a version that worked for me? 

and at least on my windows, the / no longer brings up the list of prompts. That was broken before I updated when I did have prompts synced, as well as my custom prompts... the / just stopped doing anything.

**Comment by lencx** [comment] 2022-12-23 18:11
Remember to backup your data and then empty the `~/.chatgpt` directory and let it reinitialize. https://github.com/lencx/ChatGPT/releases/tag/v0.5.1

**Comment by reconrad48** [comment] 2022-12-23 18:22
Kind of a pain, I would rather not lose all of my chat history. But I back them up and try that...

**Comment by reconrad48** [comment] 2022-12-23 19:03
Okay so that worked, I went back to the earlier version and my copied my prompt json file over to .chatgpt and it pulled them. I did want to let you know that at least my chatgpt desktop version for windows is using MS Edge webviewer and not chromium... not sure if that is what you intended or not. Just an FYI.

**Comment by reconrad48** [comment] 2022-12-23 19:03
![image](https://user-images.githubusercontent.com/71345926/209395156-b3855691-92c2-4217-a4ac-ed1425543ab4.png)

**Comment by nhan000** [comment] 2022-12-24 11:00
Hi @reconrad48 what version works on Windows for you? I'm using Windows 10 and I'm having a hard time getting it to work. Can't seem to add anything in the "Language Model" tab: can't Sync Prompts, can't Sync Custom, can't add User Custom. Struggle for the last hour and still couldn't get it to work.

**Comment by lencx** [comment] 2022-12-24 18:27
Please try v0.6.9, the problem should be fixed.

**Closed** 2022-12-27 04:28 UTC
