### ISSUE TITLE
Issue with GPT-Mobile4 Message Cap

### ISSUE THREAD

**Issue by Themegaindex** [lencx/ChatGPT#974] opened 2023-06-23 19:24 UTC
### Version

V1.0.0

Issue with GPT-Mobile4 Message Cap

### Bug description

In recent times, I've been encountering a limiting issue with GPT-Mobile4, where the application indicates a cap of 25 messages every 3 hours. As a user who interacts with this platform frequently, this limitation hinders the smooth and continuous usage of the application.

I believe an adjustment or a solution to this issue would greatly enhance the user experience and provide a more seamless interaction. I'm looking forward to hearing from you regarding possible fixes or updates that might be in the works to rectify this situation.

Thank you for your attention to this matter.

### OS

windows 11

**Comment by raymond-etet** [comment] 2023-06-26 07:10
me too ,use mobile limited 25

**Comment by yarin-zhang** [comment] 2023-06-27 03:57
This problem seems to be caused by OpenAI's implicit adjustment of the usage limit for Mobile models on June 24. Now the GPT-4 Mobile model is also subject to a limit of 25 entries every 3 hours. 

You will also encounter this prompt when you use it directly in the ChatGPT app on your phone.

It is strange that all the media avoids talking about this.

**Comment by bohuang00** [comment] 2023-06-27 08:11
According to messages from other developers on Twitter, OpenAI has addressed this "bug," and now all GPT-4 models have access limitations in terms of the number of requests.

**Comment by PEEKPerformer** [comment] 2023-06-27 11:45
I see reports that it's applied independently so you can still get double the messages.

**Comment by Themegaindex** [comment] 2023-06-28 21:42
> I see reports that it's applied independently so you can still get double the messages.

How to double the number of messages in the GPT-4 model? Can you apply this independently to get duplicate messages?

**Comment by PEEKPerformer** [comment] 2023-06-28 22:45
> > I see reports that it's applied independently so you can still get double the messages.
> 
> 
> 
> How to double the number of messages in the GPT-4 model? Can you apply this independently to get duplicate messages?

GPT-4 gives 25 messages.

GPT-4 mobile gives an additional 25 messages. The limit seems to reset in less time.

Together, you get 50 messages.

**Comment by Themegaindex** [comment] 2023-06-28 23:05
> > > I see reports that it's applied independently so you can still get double the messages.
> > 
> > 
> > How to double the number of messages in the GPT-4 model? Can you apply this independently to get duplicate messages?
> 
> GPT-4 gives 25 messages.
> 
> GPT-4 mobile gives an additional 25 messages. The limit seems to reset in less time.
> 
> Together, you get 50 messages.

regardless of which GPT-4 model I use, the use of others is restricted at the same time and I can only send a limited number of 25 messages.

**Comment by PEEKPerformer** [comment] 2023-06-30 09:37
> > > > I see reports that it's applied independently so you can still get double the messages.
> > > 
> > > 
> > > How to double the number of messages in the GPT-4 model? Can you apply this independently to get duplicate messages?
> > 
> > 
> > GPT-4 gives 25 messages.
> > GPT-4 mobile gives an additional 25 messages. The limit seems to reset in less time.
> > Together, you get 50 messages.
> 
> regardless of which GPT-4 model I use, the use of others is restricted at the same time and I can only send a limited number of 25 messages.

Same here, ether they fixed it or someone was mistaken.

**Comment by asheroto** [comment] 2023-07-01 04:45
That's not an issue with the package, it's an issue with ChatGPT. You should be able to close this issue.

This package is basically a web browser that points to ChatGPT, so it can't correct any issues that ChatGPT has.

**Closed** 2023-07-01 20:34 UTC
Labels: bug
